#!/usr/bin/env bash

# Copyright 2015 gisphm <phmfk@hotmail.com>
# Author: gisphm <phmfk@hotmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

build_dir=build
snippets_dir=neosnippets

echo "*** Updating started ***"

[[ -d $build_dir ]] && rm -rf $build_dir
mkdir -p $build_dir
echo "$build_dir directory created"

echo "cloning snippets from github"
git clone --quiet --depth=1 https://github.com/honza/vim-snippets $build_dir/vim-snippets
git clone --quiet --depth=1 https://github.com/chrisgillis/vim-bootstrap3-snippets.git $build_dir/vim-bootstrap3-snippets

echo "removing old neosnippets directory"
[[ -d $snippets_dir ]] && rm -rf $snippets_dir
mkdir -p $snippets_dir

echo "copying snippets to neosnippets directory"
cp -r $build_dir/vim-snippets/snippets/* $snippets_dir
cp -r $build_dir/vim-bootstrap3-snippets/neosnippets/* $snippets_dir

cd $snippets_dir

echo "renaming snippets to snip"
find . -maxdepth 2 -type f -name "*.snippets" | while read FNAME; do mv "$FNAME" "${FNAME//.snippets/.snip}"; done
find . -maxdepth 2 -type f -name 'snippets.snip'| while read FNAME; do mv "$FNAME" "neosnippet.snip"; done

wget -q https://github.com/justinj/vim-react-snippets/raw/master/snippets/javascript.snippets -O javascript/react.snip

echo "expanding tab in snip to spaces"
find . -maxdepth 2 -type f -name '*.snip' -exec bash -c 'expand -t 4 "$0" > /tmp/e && mv /tmp/e "$0"' '{}' \;

sub_directories=$(find * -maxdepth 0 -type d)

for dir in $sub_directories; do
    if [[ -f "$dir.snip" ]]; then
        mv "$dir.snip" $dir
    fi
done

cd ..
rm -rf $build_dir
echo "$build_dir directory removed"
echo "*** Updating completed ***"

exit
